version: "3"
services:
  hello-world-golang:
    build: hello-world-golang/
    network_mode: "host"
    restart: on-failure
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-sS", "http://localhost:3002/hello"]
      interval: 15s
      timeout: 1s
      retries: 2
      start_period: 20s
  hello-world-nodejs:
    build:
      context: hello-world-nodejs/
      args:
        NODE_BUILD_IMG_TAG: 18 # Overwritng default value from Docerfile to use newer version of node image
    network_mode: "host"
    restart: on-failure
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-sS", "http://localhost:3000/hello"]
      interval: 15s
      timeout: 1s
      retries: 2
      start_period: 20s
  hello-world-nginx:
      build: hello-world-nginx/
      network_mode: "host"
      restart: on-failure
      healthcheck:
        test: ["CMD", "/usr/bin/curl", "-sS", "http://localhost/health"]
        interval: 15s
        timeout: 1s
        retries: 2
        start_period: 30s
